apiVersion: v1
kind: Service
metadata:
  name: sample-spring-boot
  labels:
    app: sample-spring-boot
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: sample-spring-boot
